stages:
- build_image
- publish_image

docker_build:
  stage: build_image
  only:
  - master
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
  - docker build --no-cache --pull -t bdddev/unijub:latest .
  - docker tag bdddev/unijub:latest bdddev/unijub:${CI_PIPELINE_ID}
  - docker push bdddev/unijub:${CI_PIPELINE_ID}
  - docker push bdddev/unijub:latest
  tags:
    - docker
